/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KeyPointsRouteImport } from './routes/key-points'
import { Route as NoteKitRouteImport } from './routes/note-kit'
import { Route as SearchRouteImport } from './routes/search'
import { Route as BrandingIndexRouteImport } from './routes/branding/index'
import { Route as BrandingBethlehemValleyRouteImport } from './routes/branding/bethlehem-valley'
import { Route as BrandingLogoRouteImport } from './routes/branding/logo'
import { Route as SocialIndexRouteImport } from './routes/social/index'
import { Route as MentorshipsMentorshipIndexRouteImport } from './routes/mentorships/$mentorship/index'
import { Route as MentorshipsMentorshipSessionRouteImport } from './routes/mentorships/$mentorship/$session'
import { Route as MentorshipsMentorshipToCheckRouteImport } from './routes/mentorships/$mentorship/to-check'
import { Route as SocialPlatformIndexRouteImport } from './routes/social/$platform/index'
import { Route as SocialPlatformTemplateRouteImport } from './routes/social/$platform/$template'
import { Route as SocialPlatformIdeasRouteImport } from './routes/social/$platform/ideas'
import { Route as SocialPlatformPlannerRouteImport } from './routes/social/$platform/planner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyPointsRoute = KeyPointsRouteImport.update({
  id: '/key-points',
  path: '/key-points',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteKitRoute = NoteKitRouteImport.update({
  id: '/note-kit',
  path: '/note-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingIndexRoute = BrandingIndexRouteImport.update({
  id: '/branding/',
  path: '/branding/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingBethlehemValleyRoute = BrandingBethlehemValleyRouteImport.update({
  id: '/branding/bethlehem-valley',
  path: '/branding/bethlehem-valley',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingLogoRoute = BrandingLogoRouteImport.update({
  id: '/branding/logo',
  path: '/branding/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialIndexRoute = SocialIndexRouteImport.update({
  id: '/social/',
  path: '/social/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipsMentorshipIndexRoute =
  MentorshipsMentorshipIndexRouteImport.update({
    id: '/mentorships/$mentorship/',
    path: '/mentorships/$mentorship/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentorshipsMentorshipSessionRoute =
  MentorshipsMentorshipSessionRouteImport.update({
    id: '/mentorships/$mentorship/$session',
    path: '/mentorships/$mentorship/$session',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentorshipsMentorshipToCheckRoute =
  MentorshipsMentorshipToCheckRouteImport.update({
    id: '/mentorships/$mentorship/to-check',
    path: '/mentorships/$mentorship/to-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const SocialPlatformIndexRoute = SocialPlatformIndexRouteImport.update({
  id: '/social/$platform/',
  path: '/social/$platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialPlatformTemplateRoute = SocialPlatformTemplateRouteImport.update({
  id: '/social/$platform/$template',
  path: '/social/$platform/$template',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialPlatformIdeasRoute = SocialPlatformIdeasRouteImport.update({
  id: '/social/$platform/ideas',
  path: '/social/$platform/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialPlatformPlannerRoute = SocialPlatformPlannerRouteImport.update({
  id: '/social/$platform/planner',
  path: '/social/$platform/planner',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/key-points': typeof KeyPointsRoute
  '/note-kit': typeof NoteKitRoute
  '/search': typeof SearchRoute
  '/branding/bethlehem-valley': typeof BrandingBethlehemValleyRoute
  '/branding/logo': typeof BrandingLogoRoute
  '/branding/': typeof BrandingIndexRoute
  '/social/': typeof SocialIndexRoute
  '/mentorships/$mentorship/$session': typeof MentorshipsMentorshipSessionRoute
  '/mentorships/$mentorship/to-check': typeof MentorshipsMentorshipToCheckRoute
  '/social/$platform/$template': typeof SocialPlatformTemplateRoute
  '/social/$platform/ideas': typeof SocialPlatformIdeasRoute
  '/social/$platform/planner': typeof SocialPlatformPlannerRoute
  '/mentorships/$mentorship/': typeof MentorshipsMentorshipIndexRoute
  '/social/$platform/': typeof SocialPlatformIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/key-points': typeof KeyPointsRoute
  '/note-kit': typeof NoteKitRoute
  '/search': typeof SearchRoute
  '/branding/bethlehem-valley': typeof BrandingBethlehemValleyRoute
  '/branding/logo': typeof BrandingLogoRoute
  '/branding': typeof BrandingIndexRoute
  '/social': typeof SocialIndexRoute
  '/mentorships/$mentorship/$session': typeof MentorshipsMentorshipSessionRoute
  '/mentorships/$mentorship/to-check': typeof MentorshipsMentorshipToCheckRoute
  '/social/$platform/$template': typeof SocialPlatformTemplateRoute
  '/social/$platform/ideas': typeof SocialPlatformIdeasRoute
  '/social/$platform/planner': typeof SocialPlatformPlannerRoute
  '/mentorships/$mentorship': typeof MentorshipsMentorshipIndexRoute
  '/social/$platform': typeof SocialPlatformIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/key-points': typeof KeyPointsRoute
  '/note-kit': typeof NoteKitRoute
  '/search': typeof SearchRoute
  '/branding/bethlehem-valley': typeof BrandingBethlehemValleyRoute
  '/branding/logo': typeof BrandingLogoRoute
  '/branding/': typeof BrandingIndexRoute
  '/social/': typeof SocialIndexRoute
  '/mentorships/$mentorship/$session': typeof MentorshipsMentorshipSessionRoute
  '/mentorships/$mentorship/to-check': typeof MentorshipsMentorshipToCheckRoute
  '/social/$platform/$template': typeof SocialPlatformTemplateRoute
  '/social/$platform/ideas': typeof SocialPlatformIdeasRoute
  '/social/$platform/planner': typeof SocialPlatformPlannerRoute
  '/mentorships/$mentorship/': typeof MentorshipsMentorshipIndexRoute
  '/social/$platform/': typeof SocialPlatformIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/key-points'
    | '/note-kit'
    | '/search'
    | '/branding/bethlehem-valley'
    | '/branding/logo'
    | '/branding/'
    | '/social/'
    | '/mentorships/$mentorship/$session'
    | '/mentorships/$mentorship/to-check'
    | '/social/$platform/$template'
    | '/social/$platform/ideas'
    | '/social/$platform/planner'
    | '/mentorships/$mentorship/'
    | '/social/$platform/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/key-points'
    | '/note-kit'
    | '/search'
    | '/branding/bethlehem-valley'
    | '/branding/logo'
    | '/branding'
    | '/social'
    | '/mentorships/$mentorship/$session'
    | '/mentorships/$mentorship/to-check'
    | '/social/$platform/$template'
    | '/social/$platform/ideas'
    | '/social/$platform/planner'
    | '/mentorships/$mentorship'
    | '/social/$platform'
  id:
    | '__root__'
    | '/'
    | '/key-points'
    | '/note-kit'
    | '/search'
    | '/branding/bethlehem-valley'
    | '/branding/logo'
    | '/branding/'
    | '/social/'
    | '/mentorships/$mentorship/$session'
    | '/mentorships/$mentorship/to-check'
    | '/social/$platform/$template'
    | '/social/$platform/ideas'
    | '/social/$platform/planner'
    | '/mentorships/$mentorship/'
    | '/social/$platform/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KeyPointsRoute: typeof KeyPointsRoute
  NoteKitRoute: typeof NoteKitRoute
  SearchRoute: typeof SearchRoute
  BrandingBethlehemValleyRoute: typeof BrandingBethlehemValleyRoute
  BrandingLogoRoute: typeof BrandingLogoRoute
  BrandingIndexRoute: typeof BrandingIndexRoute
  SocialIndexRoute: typeof SocialIndexRoute
  MentorshipsMentorshipSessionRoute: typeof MentorshipsMentorshipSessionRoute
  MentorshipsMentorshipToCheckRoute: typeof MentorshipsMentorshipToCheckRoute
  SocialPlatformTemplateRoute: typeof SocialPlatformTemplateRoute
  SocialPlatformIdeasRoute: typeof SocialPlatformIdeasRoute
  SocialPlatformPlannerRoute: typeof SocialPlatformPlannerRoute
  MentorshipsMentorshipIndexRoute: typeof MentorshipsMentorshipIndexRoute
  SocialPlatformIndexRoute: typeof SocialPlatformIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/key-points': {
      id: '/key-points'
      path: '/key-points'
      fullPath: '/key-points'
      preLoaderRoute: typeof KeyPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note-kit': {
      id: '/note-kit'
      path: '/note-kit'
      fullPath: '/note-kit'
      preLoaderRoute: typeof NoteKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding/': {
      id: '/branding/'
      path: '/branding'
      fullPath: '/branding/'
      preLoaderRoute: typeof BrandingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding/bethlehem-valley': {
      id: '/branding/bethlehem-valley'
      path: '/branding/bethlehem-valley'
      fullPath: '/branding/bethlehem-valley'
      preLoaderRoute: typeof BrandingBethlehemValleyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding/logo': {
      id: '/branding/logo'
      path: '/branding/logo'
      fullPath: '/branding/logo'
      preLoaderRoute: typeof BrandingLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/': {
      id: '/social/'
      path: '/social'
      fullPath: '/social/'
      preLoaderRoute: typeof SocialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorships/$mentorship/': {
      id: '/mentorships/$mentorship/'
      path: '/mentorships/$mentorship'
      fullPath: '/mentorships/$mentorship/'
      preLoaderRoute: typeof MentorshipsMentorshipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorships/$mentorship/$session': {
      id: '/mentorships/$mentorship/$session'
      path: '/mentorships/$mentorship/$session'
      fullPath: '/mentorships/$mentorship/$session'
      preLoaderRoute: typeof MentorshipsMentorshipSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorships/$mentorship/to-check': {
      id: '/mentorships/$mentorship/to-check'
      path: '/mentorships/$mentorship/to-check'
      fullPath: '/mentorships/$mentorship/to-check'
      preLoaderRoute: typeof MentorshipsMentorshipToCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/$platform/': {
      id: '/social/$platform/'
      path: '/social/$platform'
      fullPath: '/social/$platform/'
      preLoaderRoute: typeof SocialPlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/$platform/$template': {
      id: '/social/$platform/$template'
      path: '/social/$platform/$template'
      fullPath: '/social/$platform/$template'
      preLoaderRoute: typeof SocialPlatformTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/$platform/ideas': {
      id: '/social/$platform/ideas'
      path: '/social/$platform/ideas'
      fullPath: '/social/$platform/ideas'
      preLoaderRoute: typeof SocialPlatformIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/$platform/planner': {
      id: '/social/$platform/planner'
      path: '/social/$platform/planner'
      fullPath: '/social/$platform/planner'
      preLoaderRoute: typeof SocialPlatformPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KeyPointsRoute: KeyPointsRoute,
  NoteKitRoute: NoteKitRoute,
  SearchRoute: SearchRoute,
  BrandingBethlehemValleyRoute: BrandingBethlehemValleyRoute,
  BrandingLogoRoute: BrandingLogoRoute,
  BrandingIndexRoute: BrandingIndexRoute,
  SocialIndexRoute: SocialIndexRoute,
  MentorshipsMentorshipSessionRoute: MentorshipsMentorshipSessionRoute,
  MentorshipsMentorshipToCheckRoute: MentorshipsMentorshipToCheckRoute,
  SocialPlatformTemplateRoute: SocialPlatformTemplateRoute,
  SocialPlatformIdeasRoute: SocialPlatformIdeasRoute,
  SocialPlatformPlannerRoute: SocialPlatformPlannerRoute,
  MentorshipsMentorshipIndexRoute: MentorshipsMentorshipIndexRoute,
  SocialPlatformIndexRoute: SocialPlatformIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
