/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KeyPointsRouteImport } from './routes/key-points'
import { Route as NoteKitRouteImport } from './routes/note-kit'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MentorshipsMentorshipIndexRouteImport } from './routes/mentorships/$mentorship/index'
import { Route as MentorshipsMentorshipSessionRouteImport } from './routes/mentorships/$mentorship/$session'
import { Route as MentorshipsMentorshipToCheckRouteImport } from './routes/mentorships/$mentorship/to-check'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyPointsRoute = KeyPointsRouteImport.update({
  id: '/key-points',
  path: '/key-points',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteKitRoute = NoteKitRouteImport.update({
  id: '/note-kit',
  path: '/note-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipsMentorshipIndexRoute =
  MentorshipsMentorshipIndexRouteImport.update({
    id: '/mentorships/$mentorship/',
    path: '/mentorships/$mentorship/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentorshipsMentorshipSessionRoute =
  MentorshipsMentorshipSessionRouteImport.update({
    id: '/mentorships/$mentorship/$session',
    path: '/mentorships/$mentorship/$session',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentorshipsMentorshipToCheckRoute =
  MentorshipsMentorshipToCheckRouteImport.update({
    id: '/mentorships/$mentorship/to-check',
    path: '/mentorships/$mentorship/to-check',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/key-points': typeof KeyPointsRoute
  '/note-kit': typeof NoteKitRoute
  '/search': typeof SearchRoute
  '/mentorships/$mentorship/$session': typeof MentorshipsMentorshipSessionRoute
  '/mentorships/$mentorship/to-check': typeof MentorshipsMentorshipToCheckRoute
  '/mentorships/$mentorship/': typeof MentorshipsMentorshipIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/key-points': typeof KeyPointsRoute
  '/note-kit': typeof NoteKitRoute
  '/search': typeof SearchRoute
  '/mentorships/$mentorship/$session': typeof MentorshipsMentorshipSessionRoute
  '/mentorships/$mentorship/to-check': typeof MentorshipsMentorshipToCheckRoute
  '/mentorships/$mentorship': typeof MentorshipsMentorshipIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/key-points': typeof KeyPointsRoute
  '/note-kit': typeof NoteKitRoute
  '/search': typeof SearchRoute
  '/mentorships/$mentorship/$session': typeof MentorshipsMentorshipSessionRoute
  '/mentorships/$mentorship/to-check': typeof MentorshipsMentorshipToCheckRoute
  '/mentorships/$mentorship/': typeof MentorshipsMentorshipIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/key-points'
    | '/note-kit'
    | '/search'
    | '/mentorships/$mentorship/$session'
    | '/mentorships/$mentorship/to-check'
    | '/mentorships/$mentorship/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/key-points'
    | '/note-kit'
    | '/search'
    | '/mentorships/$mentorship/$session'
    | '/mentorships/$mentorship/to-check'
    | '/mentorships/$mentorship'
  id:
    | '__root__'
    | '/'
    | '/key-points'
    | '/note-kit'
    | '/search'
    | '/mentorships/$mentorship/$session'
    | '/mentorships/$mentorship/to-check'
    | '/mentorships/$mentorship/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KeyPointsRoute: typeof KeyPointsRoute
  NoteKitRoute: typeof NoteKitRoute
  SearchRoute: typeof SearchRoute
  MentorshipsMentorshipSessionRoute: typeof MentorshipsMentorshipSessionRoute
  MentorshipsMentorshipToCheckRoute: typeof MentorshipsMentorshipToCheckRoute
  MentorshipsMentorshipIndexRoute: typeof MentorshipsMentorshipIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/key-points': {
      id: '/key-points'
      path: '/key-points'
      fullPath: '/key-points'
      preLoaderRoute: typeof KeyPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note-kit': {
      id: '/note-kit'
      path: '/note-kit'
      fullPath: '/note-kit'
      preLoaderRoute: typeof NoteKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorships/$mentorship/': {
      id: '/mentorships/$mentorship/'
      path: '/mentorships/$mentorship'
      fullPath: '/mentorships/$mentorship/'
      preLoaderRoute: typeof MentorshipsMentorshipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorships/$mentorship/$session': {
      id: '/mentorships/$mentorship/$session'
      path: '/mentorships/$mentorship/$session'
      fullPath: '/mentorships/$mentorship/$session'
      preLoaderRoute: typeof MentorshipsMentorshipSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorships/$mentorship/to-check': {
      id: '/mentorships/$mentorship/to-check'
      path: '/mentorships/$mentorship/to-check'
      fullPath: '/mentorships/$mentorship/to-check'
      preLoaderRoute: typeof MentorshipsMentorshipToCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KeyPointsRoute: KeyPointsRoute,
  NoteKitRoute: NoteKitRoute,
  SearchRoute: SearchRoute,
  MentorshipsMentorshipSessionRoute: MentorshipsMentorshipSessionRoute,
  MentorshipsMentorshipToCheckRoute: MentorshipsMentorshipToCheckRoute,
  MentorshipsMentorshipIndexRoute: MentorshipsMentorshipIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
